### ISSUE TITLE
Step/increment issue

### ISSUE THREAD

**Issue by Brainpiercing** [rietho/IPO#46] opened 2017-02-02 09:46 UTC
I'm trying to do an optimization of all kinds of parameters for data from LC-Orbitrap-MS, and IPO gets stuck in a loop on the ppm step for centWave. I want to optimize between 1 and 3 ppm, and it's actually trying 2.7 and 4.7 ppm and just switching between those two non-stop. 

So I'm guessing there is an issue with the step size for incremental optimization when small steps are necessary.

**Comment by rietho** [comment] 2017-02-02 18:49
Thank you for sharing this issue.
Can you reproduce this behaviour with data from some package (e.g. `faahKO` or `msdata`)?

**Comment by rietho** [comment] 2017-04-07 09:09
@Brainpiercing How about your issue?
Can you provide more info? (e.g. the output from `IPO`, the `sessionInfo()` and in the best case also your data)

**Comment by rietho** [comment] 2017-11-23 11:10
Due to no updates for several months, I'll close this issue. If there are any new infos, you're welcome to reopen the issue.

**Closed by rietho** 2017-11-23 11:10 UTC
